version: "3"

services:
  prodmais:
    container_name: prodmais
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./prodmais:/var/www/html/prodmais
      - ./esdata:/tmp/elastic
    environment:
      - TIMEZONE=Etc/GMT-3
    ports:
      - "80:80"
    networks:
      - elastic
    tty: true
    command: >
      bash -c '
        service apache2 start;
        service apache2 status;
        service elasticsearch start;
        service elasticsearch status;
        bash;
      '

volumes:
  prodmais:
    driver: local

networks:
  elastic:
    driver: bridge